### ISSUE TITLE
Section 2: Application Design

### ISSUE THREAD

**Issue by dustinRDF** [dustinRDF/food-roulette#25]
- **Frontend Design**
- [ ] What programming languages will be used? #6
- [ ] Create a wireframe of the  user interface. #7
- [ ] Describe how the application flows from one screen to the next. #8
- **Backend Design**
- [ ] What kind of database will be used? #9
- [ ] What kind of data will be stored in the database? #9
- [ ] What languages will be used? #10
