### ISSUE TITLE
Section 3: Development

### ISSUE THREAD

**Issue by dustinRDF** [dustinRDF/food-roulette#26]
- **Development**
- [x] Create a project structure #17
- [x] Setup the express server #18
- [x] Setup the front end (angular) #19
- [x] Setup routing #20
- [x] Setup components #21
- [x] Setup services #22

**Comment by dustinRDF** [comment]
Task complete via commits 5fa7bf232959d32c20d9d03f8f3e29bebc78a15b and e1863a0f676b4116c9424180d90ae1fd8f0ea36c
